# Generated by Django 5.1.15 on 2026-06-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='profile',
            field=models.CharField(choices=[('regular', 'Vanlig cykel'), ('road', 'Landsväg'), ('mountain', 'Mountainbike'), ('electric', 'Elcykel')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='stage',
            name='from_point',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='stage',
            name='to_point',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
