# Generated by Django 5.1.15 on 2026-06-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_stage_profile_alter_stage_from_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='is_rest_day',
            field=models.BooleanField(default=False, help_text='Vilodag – ingen cykling denna dag.'),
        ),
    ]
