# Generated by Django 5.1.15 on 2026-06-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_day_is_rest_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='countries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
