# Generated by Django 5.1.15 on 2026-06-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_stage_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='auto_from',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stage',
            name='auto_to',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
