# Generated by Django 5.1.15 on 2026-06-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_stage_auto_from_stage_auto_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rider_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='rider_gender',
            field=models.CharField(blank=True, choices=[('M', 'Man'), ('F', 'Kvinna'), ('O', 'Annat / vill ej ange')], max_length=1),
        ),
        migrations.AddField(
            model_name='project',
            name='rider_height_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='rider_weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
