# Generated by Django 5.1.15 on 2026-06-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_project_rider_age_project_rider_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='from_country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='stage',
            name='to_country',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
