# Generated by Django 5.1.15 on 2026-06-24 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_stage_from_country_stage_to_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='actual_distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='actual_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='actual_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('EXPENSE', 'Utgift'), ('NOTE', 'Anteckning'), ('INCIDENT', 'Händelse')], default='NOTE', max_length=10)),
                ('text', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(blank=True, choices=[('RESA', 'Resa'), ('BOENDE', 'Boende'), ('SERVICE', 'Service'), ('NOJE', 'Nöje'), ('FRUKOST', 'Frukost'), ('LUNCH', 'Lunch'), ('MIDDAG', 'Middag'), ('KVALLSMAT', 'Kvällsmat'), ('MELLANMAL', 'Mellanmål'), ('DRICKA', 'Dricka')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='planner.day')),
            ],
            options={
                'verbose_name_plural': 'log entries',
                'ordering': ['created_at'],
            },
        ),
    ]
