# Generated by Django 5.1.15 on 2026-06-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_day_actual_distance_km_day_actual_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='actual_track',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
