# Generated by Django 5.1.15 on 2026-06-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_day_actual_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='route_steps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
